apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../production.yml convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: django
status:
  loadBalancer: {}
